### ISSUE TITLE
potential fix for docker-in-docker

### ISSUE THREAD

**Issue by kaczmarj** [95616ARG/SyReNN#7]
i noticed that [the readme says](https://github.com/95616ARG/SyReNN/blob/master/README.md#docker-builds)

> __NOTE:__ Docker-in-docker does not seem to currently be working. 

have you tried mounting the docker socket into the container? you can use these arguments in `docker run`.

```
-v /var/run/docker.sock:/var/run/docker.sock
```

**Comment by matthewsot** [comment]
Thanks for pointing this out! So far, it hasn't been a huge issue, but if anyone wants to try and get this working + test this solution it's great to have the tip.

**Comment by matthewsot** [comment]
I've added a link to this in the readme as part of #9. If anyone wants to make the changes to the scripts throughout + confirm that it works, feel free to send a PR. But for now hopefully this gives interested people enough of a pointer to chase down :) Thanks again!
